notifications:
  slack: aura-4wf6714:fSvcq8RpdYOo6Jg8BOgoiXzV

language: node_js
node_js:
  - "10.15.2"
script:
  - echo "Deploying"

before_script:
  - npm install -g firebase-tools
  - npm install -g @vue/cli@latest
  - npm install

script:
  - npm run build

after_success:  
  - firebase deploy --token $FKEY
